### ISSUE TITLE
Publish on open-vsx.org?

### ISSUE THREAD

**Issue by dixiekong** [reliut-g/bulma-css-class-completion#3]
Would you consider publishing this extension on the [OpenVSX Registry](https://open-vsx.org/)? 
By doing so you would enable users of [VSCodium](https://vscodium.com/) to install this extension.
Instructions how this can be done can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by roberthgnz** [comment]
Thank you for your suggestion. I will do some research and see when I can make the extension public in OpenVSX Registry.

**Comment by dixiekong** [comment]
Thanks a lot.

**Comment by roberthgnz** [comment]
Bulma CSS Class Completion

https://open-vsx.org/extension/eliutdev/bulma-css-class-completion
