### ISSUE TITLE
Class completion for .js file extension (react)

### ISSUE THREAD

**Issue by ContrerasA** [reliut-g/bulma-css-class-completion#4]
Looking to see if we can get completion to also work with the .js file extension for react.
React needs the classes to go in the className attribute of each html element.

ex: 
<div className="is-column"></div>

**Comment by roberthgnz** [comment]
Hi @ContrerasA 
Thank you for your interest in the extension. I have made the improvements, now in version [0.3.0](https://marketplace.visualstudio.com/items?itemName=reliutg.bulma-css-class-completion) you will be able to use it with **react**, `(js, jsx)`.
