### ISSUE TITLE
autocompletion not triggering on partial autocompletion

### ISSUE THREAD

**Issue by ebursztein** [reliut-g/bulma-css-class-completion#6]
The autocompletion is not working in the following scenario:
have a half class writing such as `<div class="is-">`  then asking to autocomplete (to avoid the full list doesn't work).

**Comment by eliutdev** [comment]
Hi @ebursztein thanks for reporting this issue. I have had a look at it, however I still don't understand the problem scenario you have raised. could you give me more context?

**Comment by roberthgnz** [comment]
@ebursztein thank you for reporting. I will work on it

**Comment by roberthgnz** [comment]
Hi @ebursztein 0.3.2 version is now available. If you update it you should no longer have this problem.
