### ISSUE TITLE
Compatibility for .php extension or any other extension

### ISSUE THREAD

**Issue by Eisteed** [reliut-g/bulma-css-class-completion#7]
Hey, nice plugin working great when editing .html but when editing .php there's no possibility to enable the autocomplete feature.
Can you add to the plugin the possibility of enabling it on any file type ? Or using configuration so we can enter manually which type of file extension we need .

Thanks

**Comment by Eisteed** [comment]
Think I fixed it by adding this to my settings.json

    "emmet.includeLanguages": {
        "php": "html"
    }

**Comment by roberthgnz** [comment]
It's great that you got it sorted out. Thanks for sharing!
