### ISSUE TITLE
Nothing shows up

### ISSUE THREAD

**Issue by Sprocketer** [reliut-g/bulma-css-class-completion#9]
Nothing's showing up for me when I try using it - do you know any possible reason why? I did check the extension settings, html is in the list for languages.

**Comment by roberthgnz** [comment]
Hi @Sprocketer 

I have uploaded a bugfix version, upgrade to version [0.9.0](https://marketplace.visualstudio.com/items?itemName=reliutg.bulma-css-class-completion)
